### ISSUE TITLE
:wave: Hey there!

### ISSUE THREAD

**Issue by spamegg1** [ossu/spd-starters#6]
_Looks like you guys took this..._

...either from my repo, or the zip files I pinned on Discord back then.

It even has screenshots I took myself back in 2018! (I remember that brown Windows 7 theme I made, I was really into "coffee themes" back then.)

I drew that `vk.png` image to explain the complicated recursion for the Van Koch fractal to someone!

I mean, I don't mind of course, and the license obviously permits it. No complaints / accusations :laughing: 

*But a little heads-up would have been nice.* I'm still friends with both of you on Discord I think? Maybe at least mention me in the README? It feels kinda... weird.

It's nice to see all that hard work I did back then paid off, seems like you guys escaped the grasp of edX deadlines and moved it back to Systematic Program Design. At least this should provide some freedom and independence for the learners.

I'm happy, really.

Anyway...

I had removed all the "Dr Racket metadata" from the files, because some of them were thousands of lines long and polluting my repo. Did you have to add those back? *That must have been painful. My condolences to your copy/paste fingers.*

Or maybe I had some versions *with* the metadata laying around somewhere? Can't remember.

I took a different approach and rewrote all these courses in Scala:

https://github.com/user-attachments/assets/59526569-e9ec-4259-9573-f9b85ec9814b

**BUT I'M NOT SHARING THAT ONE!** :laughing: :laughing: :laughing: 

Feel free to close this issue. Good luck!

**Comment by waciumawanjohi** [comment]
Hi @spamegg1 , I've sent you a message in Discord. Definitely want to get to the bottom of this!
